app:
  title: Internal Developer Platform
  baseUrl: http://35.188.96.202

organization:
  name: DevOpsSimplify

backend:
  baseUrl: http://35.188.96.202
  listen:
    port: 7007
    host: 0.0.0.0
  csp:
    connect-src: ["'self'", 'http:', 'https:']
    upgrade-insecure-requests: false
  headers:
    Strict-Transport-Security: false
  cors:
    origin: http://35.188.96.202
    methods: [GET, HEAD, PATCH, POST, PUT, DELETE]
    credentials: true
  database:
    client: pg
    connection:
      host: ${POSTGRES_HOST}
      port: ${POSTGRES_PORT}
      user: ${POSTGRES_USER}
      password: ${POSTGRES_PASSWORD}
      database: backstage

integrations:
  github:
    - host: github.com
      token: ${GITHUB_TOKEN}

auth:
  providers:
    guest:
      dangerouslyAllowOutsideDevelopment: true

scaffolder:
  defaultAuthor:
    name: Backstage Scaffolder
    email: scaffolder@backstage.io
  defaultCommitMessage: 'Scaffolded by Backstage'

catalog:
  import:
    entityFilename: catalog-info.yaml
    pullRequestBranchName: backstage-integration
  rules:
    - allow: [Component, System, API, Resource, Location, Template, User, Group]
  providers:
    github:
      idp-catalog:
        organization: devopssimplify
        catalogPath: /catalog/*.yaml
        filters:
          repository: backstage-idp
        schedule:
          frequency: { minutes: 5 }
          timeout: { minutes: 3 }
        orphanStrategy: delete
  locations:
    - type: file
      target: ./templates/provision-environment/template.yaml
      rules:
        - allow: [Template]
    - type: file
      target: ./templates/deploy-application/template.yaml
      rules:
        - allow: [Template]
    - type: file
      target: ./templates/provision-cockroachdb/template.yaml
      rules:
        - allow: [Template]
    - type: file
      target: ./templates/provision-kafka/template.yaml
      rules:
        - allow: [Template]
    - type: file
      target: ./templates/provision-kafka-topics/template.yaml
      rules:
        - allow: [Template]
    - type: file
      target: ./templates/delete-environment/template.yaml
      rules:
        - allow: [Template]
    - type: file
      target: ./templates/delete-infrastructure/template.yaml
      rules:
        - allow: [Template]
    - type: file
      target: ./templates/delete-kafka-cluster/template.yaml
      rules:
        - allow: [Template]
    - type: file
      target: ./templates/delete-kafka-topics/template.yaml
      rules:
        - allow: [Template]
    - type: file
      target: ./templates/update-network-code/template.yaml
      rules:
        - allow: [Template]

gcpBilling:
  projectId: project-7d27fad9-61bb-42c4-b2e
  dataset: idp_ds
  table: gcp_billing_export_v1_015DCD_5E65E7_01231F

kubernetes:
  serviceLocatorMethod:
    type: 'multiTenant'
  clusterLocatorMethods:
    - type: 'config'
      clusters:
        - url: ${K8S_CLUSTER_URL}
          name: gke-cluster
          authProvider: 'serviceAccount'
          serviceAccountToken: ${K8S_SERVICE_ACCOUNT_TOKEN}
          skipTLSVerify: true
          skipMetricsLookup: false
