{%- for topic in values.topics %}
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: ${{ values.namePrefix }}-${{ topic.topicName }}
  namespace: ${{ values.environment }}
  labels:
    strimzi.io/cluster: ${{ values.clusterName }}
    team: ${{ values.team }}
    managed-by: backstage
spec:
  partitions: ${{ topic.partitions }}
  replicas: ${{ topic.replicationFactor if topic.replicationFactor else 1 }}
  config:
    retention.ms: "${{ topic.retentionHours * 3600000 if topic.retentionHours else 604800000 }}"
    segment.bytes: "1073741824"
{%- endfor %}
