---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: pds-ui
  description: "pds-ui deployed to pds-510 by IDP"
  annotations:
    backstage.io/kubernetes-id: pds-ui
    backstage.io/kubernetes-namespace: pds-510
    backstage.io/kubernetes-label-selector: app=pds-ui
  tags:
    - application
    - pds-510
    - idp-managed
    - network-code-cn580005
  links:
    - title: GitOps Source
      url: https://github.com/devopssimplify/idp-poc-gitops/blob/main/apps/pds-510/pds-ui.yaml
      icon: github
spec:
  type: service
  lifecycle: pds-510
  owner: group:default/backend
  system: CN580005
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: CN580005
  description: "Network code CN580005 — all resources billed to this cost center"
  tags:
    - network-code
    - idp-managed
spec:
  owner: group:default/backend
