---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: pds-509-namespace
  description: "pds-509 namespace environment"
  tags:
    - namespace
    - environment
    - idp-managed
    - network-code-cn580004
  links:
    - title: GitOps Source
      url: https://github.com/devopssimplify/idp-poc-gitops/blob/main/cluster/namespace-pds-509.yaml
      icon: github
spec:
  type: environment
  lifecycle: production
  owner: group:default/platform
  system: CN580004
