---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: pds-kafka
  description: test
  annotations:
    backstage.io/kubernetes-id: pds-kafka
    backstage.io/kubernetes-namespace: dev
    backstage.io/kubernetes-label-selector: strimzi.io/cluster=pds-kafka
  tags:
    - kafka
    - message-broker
    - dev
    - idp-managed
    - network-code-cn580005
  links:
    - title: GitOps Source
      url: https://github.com/devopssimplify/idp-poc-gitops/blob/main/infra/kafka-pds-kafka.yaml
      icon: github
spec:
  type: message-broker
  lifecycle: dev
  owner: group:default/platform
  system: CN580005
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: CN580005
  description: "Network code CN580005 — all resources billed to this cost center"
  tags:
    - network-code
    - idp-managed
spec:
  owner: group:default/platform
