---
apiVersion: databases.schemahero.io/v1alpha4
kind: Database
metadata:
  name: ${{ values.databaseName }}
  namespace: ${{ values.environment }}
  labels:
    app: cockroachdb-${{ values.databaseName }}
    team: ${{ values.team }}
    managed-by: backstage
spec:
  connection:
    postgres:
      host:
        value: cockroachdb-${{ values.databaseName }}.${{ values.environment }}.svc.cluster.local
      port:
        value: "26257"
      user:
        value: root
      dbname:
        value: ${{ values.schemaName }}
      sslmode:
        value: disable
