---
apiVersion: databases.schemahero.io/v1alpha4
kind: Database
metadata:
  name: ${{ values.databaseName }}
  namespace: ${{ values.environment }}
  labels:
    app: cockroachdb-${{ values.databaseName }}
    team: ${{ values.team }}
    managed-by: backstage
spec:
  connection:
    postgres:
      uri:
        value: postgresql://root@cockroachdb-${{ values.databaseName }}.${{ values.environment }}.svc.cluster.local:26257/${{ values.schemaName }}?sslmode=disable
