---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: ${{ values.namePrefix }}-kafka
  description: ${{ values.description if values.description else "Kafka cluster managed by IDP" }}
  annotations:
    backstage.io/kubernetes-id: ${{ values.namePrefix }}-kafka
    backstage.io/kubernetes-namespace: ${{ values.environment }}
    backstage.io/kubernetes-label-selector: strimzi.io/cluster=${{ values.namePrefix }}-kafka
  tags:
    - kafka
    - message-broker
    - ${{ values.environment }}
    - idp-managed
    - network-code-${{ values.networkCode | lower }}
  links:
    - title: GitOps Source
      url: https://github.com/devopssimplify/idp-poc-gitops/blob/main/infra/kafka-${{ values.clusterName }}.yaml
      icon: github
spec:
  type: message-broker
  lifecycle: ${{ values.environment }}
  owner: group:default/${{ values.team }}
  system: ${{ values.networkCode }}
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: ${{ values.networkCode }}
  description: "Network code ${{ values.networkCode }} — all resources billed to this cost center"
  tags:
    - network-code
    - idp-managed
spec:
  owner: group:default/${{ values.team }}
