{%- if values.enableMemorystore %}
apiVersion: redis.cnrm.cloud.google.com/v1beta1
kind: RedisInstance
metadata:
  name: ${{ values.environmentName }}-redis
  namespace: config-connector
  labels:
    network-code: ${{ values.networkCode | lower }}
    team: ${{ values.team }}
    managed-by: backstage
  annotations:
    cnrm.cloud.google.com/project-id: ${{ values.gcpProject }}
spec:
  memorySizeGb: 1
  region: us-central1
  tier: BASIC
  redisVersion: REDIS_7_0
  displayName: Redis for ${{ values.environmentName }}
  authorizedNetworkRef:
    name: default
  connectMode: DIRECT_PEERING
{%- endif %}
